openapi: 3.0.0
servers:
  - description: Assessment
    url: http://localhost:3000
info:
  version: "1.0.0",
    title: assessment-app
    description: Assessment App

tags:
  - name: Auth
    description: Аутентификация

paths:
  /api/login:
    post:
      summary: Авторизоваться
      tags:
        - Auth
      operationId: apiLogin
      requestBody:
        $ref: "#/components/requestBodies/ApiAuth"
      responses:
        "200":
          description: Ответ
          content:
            "application/json":
              schema:
                type: string
                title: Ответ запроса





components:
  requestBodies:
    ApiAuth:
      description: Тело запроса на авторизацию
      content:
        'application/json':
          schema:
            type: object
            title: Запрос
            properties:
              email:
                type: string
                title: email пользователя
              password:
                type: string
                title: Пароль
